[build]
builder = "nixpacks"
buildCommand = "cd frontend && yarn install && yarn build"

[deploy]
startCommand = "cd frontend && npx serve -s build -l $PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[nixpacks]
nixpkgsVersion = "nixos-22.11"
